ame: "hola mundo"

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola mundo desde GitHub Actions"
      - run: echo "Este es un ejemplo de un workflow simple"
      - run: echo "Puedes personalizarlo según tus necesidades"

    
 
        - 
