name: deploy service
on: push
jobs:
  first-job:
    env:
      NAME: "Ricardo"
    runs-on: ubuntu-latest
    outputs:
      mi_var: ${{ steps.concatenado.outputs.mi_var }}
    steps:
      - name: hola mundo
        run: echo "Hola mundo desde GitHub Actions ${NAME}"

      - name: working dir
        run: ls -al

      - name: actions/checkout
        uses: actions/checkout@v4

      - name: working dir
        run: ls -al

      - name: concatenado variables
        id: concatenado
        run: echo "mi_var=prueba" >> $GITHUB_OUTPUT

      - name: mostrar variable
        run: echo "La variable mi_var es:${{ steps.concatenado.outputs.mi_var }}"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest

    env:
      VALOR: "${{ needs.first-job.outputs.mi_var }}"

    steps:
      - name: hola mundo 2
        run: echo "Hola mundo desde GitHub Actions 2"
      - name: mostrar variable de primer job
        run: echo "La variable mi_var del primer job es: ${{VALOR}}

