name: Strategy
on: push
jobs:
  multi-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: prueba
        run: echo "Hola mundo desde GitHub Actions en ${{ matrix.os }}"
      